# Windows runtime DLL helpers (vcpkg only — never scan System32 or install/bin).

function(rocketbox_resolve_vcpkg_bin out_var)
    if(NOT VCPKG_TARGET_TRIPLET)
        set(_triplet "x64-windows")
    else()
        set(_triplet "${VCPKG_TARGET_TRIPLET}")
    endif()

    set(_candidates "")
    if(VCPKG_INSTALLED_DIR)
        list(APPEND _candidates "${VCPKG_INSTALLED_DIR}/${_triplet}/bin")
    endif()
    list(APPEND _candidates
        "${CMAKE_BINARY_DIR}/vcpkg_installed/${_triplet}/bin"
        "${CMAKE_SOURCE_DIR}/vcpkg_installed/${_triplet}/bin"
    )

    set(_found "")
    foreach(_dir IN LISTS _candidates)
        if(_dir AND IS_DIRECTORY "${_dir}")
            set(_found "${_dir}")
            break()
        endif()
    endforeach()

    set(${out_var} "${_found}" PARENT_SCOPE)
endfunction()

# Bundle every runtime DLL vcpkg installed for this triplet (wx/libusb pull in z.dll, liblzma, etc.).
function(rocketbox_collect_vcpkg_runtime_dlls vcpkg_bin out_var)
    set(_collected "")
    if(vcpkg_bin AND IS_DIRECTORY "${vcpkg_bin}")
        file(GLOB _collected "${vcpkg_bin}/*.dll")
    endif()
    set(${out_var} "${_collected}" PARENT_SCOPE)
endfunction()

function(rocketbox_assert_vcpkg_runtime_dlls dll_list vcpkg_bin)
    set(_has_libusb FALSE)
    set(_has_wx FALSE)
    set(_has_zlib FALSE)
    set(_has_lzma FALSE)
    foreach(_dll IN LISTS dll_list)
        get_filename_component(_name "${_dll}" NAME)
        if(_name STREQUAL "libusb-1.0.dll")
            set(_has_libusb TRUE)
        endif()
        if(_name MATCHES "^wx.*\\.dll$")
            set(_has_wx TRUE)
        endif()
        if(_name MATCHES "^(z|zlib).*\\.dll$")
            set(_has_zlib TRUE)
        endif()
        if(_name MATCHES "^(lib)?lzma.*\\.dll$")
            set(_has_lzma TRUE)
        endif()
    endforeach()

    if(NOT _has_libusb)
        message(FATAL_ERROR "Windows: libusb-1.0.dll not found in ${vcpkg_bin}")
    endif()
    if(NOT _has_wx)
        message(FATAL_ERROR "Windows: no wx*.dll found in ${vcpkg_bin}")
    endif()
    if(NOT _has_zlib)
        message(FATAL_ERROR "Windows: no z.dll/zlib*.dll found in ${vcpkg_bin}")
    endif()
    if(NOT _has_lzma)
        message(FATAL_ERROR "Windows: no liblzma*.dll found in ${vcpkg_bin}")
    endif()
endfunction()
