export {
  VENDOR_ID,
  PRODUCT_ID,
  INTERFACE_NUMBER,
  EP_OUT,
  EP_IN,
  HEADER_SIZE,
  CHUNK_SIZE,
  HEADER_MAGIC,
  buildHeader,
  parseHeader,
  concatChunks,
  boothDisplayMibSWithJitter,
  rollBoothDisplayMibS,
  type ParsedHeader,
} from '@rocketbox/sdk';
